version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven..."
      - mvn --version
  build:
    commands:
      - echo "Building WAR package..."
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/maven-cloudaseem-app.war
    - appspec.yml
    - scripts/**        # your deployment scripts if any
